# Generated by Django 2.2.1 on 2019-05-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('location', models.CharField(max_length=40, verbose_name='Location')),
                ('ip_address', models.GenericIPAddressField(editable=False, verbose_name='IP Address')),
            ],
            options={
                'db_table': 'onsign_tracker',
            },
        ),
    ]
