# Generated by Django 2.2.1 on 2019-05-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='consulted',
            field=models.BooleanField(default=True, verbose_name='Consulted'),
        ),
    ]
