# Generated by Django 2.2.1 on 2019-05-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_tracker_consulted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='consulted',
            field=models.BooleanField(default=True, editable=False, verbose_name='Consulted'),
        ),
    ]
